name: Checkout | Make envs | Commit away

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo from where to get content'
        required: true
      pat:
        description: 'Account personal access token'
        required: true
      safe:
        description: 'Url of @safe'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Print source repository
      run: echo "Hello ${{ inputs.source_repo }}"

    - name: Print source repository
      run: echo ${{ github.event.inputs.source_repo }}

    - name: Display input parameters
      run: |
        echo "Repository: ${{ github.event.inputs.repo }}"
        echo "Personal Access Token: ${{ github.event.inputs.pat }}"
        echo "Safe URL: ${{ github.event.inputs.safe }}"
